spring:
  application:
    name: ${rootProjectName}-server

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: ${FLYWAY_ENABLED:false}

  profiles:
    active:
      - local

server:
  error:
    include-message: never
